name: BookExploitFix
version: ${project.version}
main: me.jndildap.bukkit.bookexploit.BookExploitFix
author: jndildap
description: ${project.description}
website: '${project.url}'
api-version: 1.13
softdepend: [ ProtocolLib ]
commands:
  filter:
    aliases: [ bookfilter, filterbook ]
    usage: /<command>
    permission: bookfilter.filter
