name: BookExploitFix
version: 1.4
main: me.jndildap.bukkit.bookexploit.BookExploitFix
author: jndildap
description: Fixes an exploit with JSON books
website: 'https://github.com/me-jndildap/BookExploitFix'
api-version: 1.13
softdepend: [ ProtocolLib ]
commands:
  filter:
    aliases: [ bookfilter, filterbook ]
    usage: /<command>
    permission: bookfilter.filter
